# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pyro/Projekte/STM32F103/STM32F103C8_DCF77

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pyro/Projekte/STM32F103/STM32F103C8_DCF77

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pyro/Projekte/STM32F103/STM32F103C8_DCF77/CMakeFiles /home/pyro/Projekte/STM32F103/STM32F103C8_DCF77/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pyro/Projekte/STM32F103/STM32F103C8_DCF77/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stm32f103Demo.elf

# Build rule for target.
stm32f103Demo.elf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stm32f103Demo.elf
.PHONY : stm32f103Demo.elf

# fast build rule for target.
stm32f103Demo.elf/fast:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/build
.PHONY : stm32f103Demo.elf/fast

lib/CMSIS/startup_stm32f10x_md.o: lib/CMSIS/startup_stm32f10x_md.c.o
.PHONY : lib/CMSIS/startup_stm32f10x_md.o

# target to build an object file
lib/CMSIS/startup_stm32f10x_md.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/CMSIS/startup_stm32f10x_md.c.o
.PHONY : lib/CMSIS/startup_stm32f10x_md.c.o

lib/CMSIS/startup_stm32f10x_md.i: lib/CMSIS/startup_stm32f10x_md.c.i
.PHONY : lib/CMSIS/startup_stm32f10x_md.i

# target to preprocess a source file
lib/CMSIS/startup_stm32f10x_md.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/CMSIS/startup_stm32f10x_md.c.i
.PHONY : lib/CMSIS/startup_stm32f10x_md.c.i

lib/CMSIS/startup_stm32f10x_md.s: lib/CMSIS/startup_stm32f10x_md.c.s
.PHONY : lib/CMSIS/startup_stm32f10x_md.s

# target to generate assembly for a file
lib/CMSIS/startup_stm32f10x_md.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/CMSIS/startup_stm32f10x_md.c.s
.PHONY : lib/CMSIS/startup_stm32f10x_md.c.s

lib/CMSIS/system_stm32f10x.o: lib/CMSIS/system_stm32f10x.c.o
.PHONY : lib/CMSIS/system_stm32f10x.o

# target to build an object file
lib/CMSIS/system_stm32f10x.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/CMSIS/system_stm32f10x.c.o
.PHONY : lib/CMSIS/system_stm32f10x.c.o

lib/CMSIS/system_stm32f10x.i: lib/CMSIS/system_stm32f10x.c.i
.PHONY : lib/CMSIS/system_stm32f10x.i

# target to preprocess a source file
lib/CMSIS/system_stm32f10x.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/CMSIS/system_stm32f10x.c.i
.PHONY : lib/CMSIS/system_stm32f10x.c.i

lib/CMSIS/system_stm32f10x.s: lib/CMSIS/system_stm32f10x.c.s
.PHONY : lib/CMSIS/system_stm32f10x.s

# target to generate assembly for a file
lib/CMSIS/system_stm32f10x.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/CMSIS/system_stm32f10x.c.s
.PHONY : lib/CMSIS/system_stm32f10x.c.s

lib/STM32F10x_StdPeriph_Driver/src/misc.o: lib/STM32F10x_StdPeriph_Driver/src/misc.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/misc.o

# target to build an object file
lib/STM32F10x_StdPeriph_Driver/src/misc.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/misc.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/misc.c.o

lib/STM32F10x_StdPeriph_Driver/src/misc.i: lib/STM32F10x_StdPeriph_Driver/src/misc.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/misc.i

# target to preprocess a source file
lib/STM32F10x_StdPeriph_Driver/src/misc.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/misc.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/misc.c.i

lib/STM32F10x_StdPeriph_Driver/src/misc.s: lib/STM32F10x_StdPeriph_Driver/src/misc.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/misc.s

# target to generate assembly for a file
lib/STM32F10x_StdPeriph_Driver/src/misc.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/misc.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/misc.c.s

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.o: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.o

# target to build an object file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c.o

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.i: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.i

# target to preprocess a source file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c.i

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.s: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.s

# target to generate assembly for a file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c.s

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.o: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.o

# target to build an object file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c.o

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.i: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.i

# target to preprocess a source file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c.i

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.s: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.s

# target to generate assembly for a file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c.s

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.o: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.o

# target to build an object file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.c.o

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.i: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.i

# target to preprocess a source file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.c.i

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.s: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.s

# target to generate assembly for a file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.c.s

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.o: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.o

# target to build an object file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.c.o

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.i: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.i

# target to preprocess a source file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.c.i

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.s: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.s

# target to generate assembly for a file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.c.s

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.o: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.o

# target to build an object file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.c.o

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.i: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.i

# target to preprocess a source file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.c.i

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.s: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.s

# target to generate assembly for a file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.c.s

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.o: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.o

# target to build an object file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c.o

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.i: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.i

# target to preprocess a source file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c.i

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.s: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.s

# target to generate assembly for a file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c.s

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.o: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.o

# target to build an object file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c.o

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.i: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.i

# target to preprocess a source file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c.i

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.s: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.s

# target to generate assembly for a file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c.s

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.o: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.o

# target to build an object file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c.o

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.i: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.i

# target to preprocess a source file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c.i

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.s: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.s

# target to generate assembly for a file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c.s

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.o: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.o

# target to build an object file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c.o

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.i: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.i

# target to preprocess a source file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c.i

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.s: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.s

# target to generate assembly for a file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c.s

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.o: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.o

# target to build an object file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c.o

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.i: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.i

# target to preprocess a source file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c.i

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.s: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.s

# target to generate assembly for a file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c.s

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.o: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.o

# target to build an object file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c.o

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.i: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.i

# target to preprocess a source file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c.i

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.s: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.s

# target to generate assembly for a file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c.s

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.o: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.o

# target to build an object file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c.o

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.i: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.i

# target to preprocess a source file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c.i

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.s: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.s

# target to generate assembly for a file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c.s

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.o: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.o

# target to build an object file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c.o

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.i: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.i

# target to preprocess a source file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c.i

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.s: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.s

# target to generate assembly for a file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c.s

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.o: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.o

# target to build an object file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.c.o

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.i: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.i

# target to preprocess a source file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.c.i

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.s: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.s

# target to generate assembly for a file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.c.s

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.o: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.o

# target to build an object file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c.o

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.i: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.i

# target to preprocess a source file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c.i

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.s: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.s

# target to generate assembly for a file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c.s

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.o: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.o

# target to build an object file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c.o

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.i: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.i

# target to preprocess a source file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c.i

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.s: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.s

# target to generate assembly for a file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c.s

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.o: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.o

# target to build an object file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.c.o

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.i: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.i

# target to preprocess a source file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.c.i

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.s: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.s

# target to generate assembly for a file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.c.s

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.o: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.o

# target to build an object file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c.o

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.i: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.i

# target to preprocess a source file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c.i

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.s: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.s

# target to generate assembly for a file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c.s

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.o: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.o

# target to build an object file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.c.o

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.i: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.i

# target to preprocess a source file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.c.i

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.s: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.s

# target to generate assembly for a file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.c.s

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.o: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.o

# target to build an object file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c.o

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.i: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.i

# target to preprocess a source file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c.i

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.s: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.s

# target to generate assembly for a file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c.s

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.o: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.o

# target to build an object file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c.o

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.i: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.i

# target to preprocess a source file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c.i

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.s: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.s

# target to generate assembly for a file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c.s

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.o: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.o

# target to build an object file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.c.o
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.c.o

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.i: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.i

# target to preprocess a source file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.c.i
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.c.i

lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.s: lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.s

# target to generate assembly for a file
lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.c.s
.PHONY : lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.c.s

lib/syscalls/syscalls.o: lib/syscalls/syscalls.c.o
.PHONY : lib/syscalls/syscalls.o

# target to build an object file
lib/syscalls/syscalls.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/syscalls/syscalls.c.o
.PHONY : lib/syscalls/syscalls.c.o

lib/syscalls/syscalls.i: lib/syscalls/syscalls.c.i
.PHONY : lib/syscalls/syscalls.i

# target to preprocess a source file
lib/syscalls/syscalls.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/syscalls/syscalls.c.i
.PHONY : lib/syscalls/syscalls.c.i

lib/syscalls/syscalls.s: lib/syscalls/syscalls.c.s
.PHONY : lib/syscalls/syscalls.s

# target to generate assembly for a file
lib/syscalls/syscalls.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/lib/syscalls/syscalls.c.s
.PHONY : lib/syscalls/syscalls.c.s

src/dcf77.o: src/dcf77.c.o
.PHONY : src/dcf77.o

# target to build an object file
src/dcf77.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/src/dcf77.c.o
.PHONY : src/dcf77.c.o

src/dcf77.i: src/dcf77.c.i
.PHONY : src/dcf77.i

# target to preprocess a source file
src/dcf77.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/src/dcf77.c.i
.PHONY : src/dcf77.c.i

src/dcf77.s: src/dcf77.c.s
.PHONY : src/dcf77.s

# target to generate assembly for a file
src/dcf77.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/src/dcf77.c.s
.PHONY : src/dcf77.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/src/main.c.s
.PHONY : src/main.c.s

src/stm32f10x_it.o: src/stm32f10x_it.c.o
.PHONY : src/stm32f10x_it.o

# target to build an object file
src/stm32f10x_it.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/src/stm32f10x_it.c.o
.PHONY : src/stm32f10x_it.c.o

src/stm32f10x_it.i: src/stm32f10x_it.c.i
.PHONY : src/stm32f10x_it.i

# target to preprocess a source file
src/stm32f10x_it.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/src/stm32f10x_it.c.i
.PHONY : src/stm32f10x_it.c.i

src/stm32f10x_it.s: src/stm32f10x_it.c.s
.PHONY : src/stm32f10x_it.s

# target to generate assembly for a file
src/stm32f10x_it.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/src/stm32f10x_it.c.s
.PHONY : src/stm32f10x_it.c.s

src/systick.o: src/systick.c.o
.PHONY : src/systick.o

# target to build an object file
src/systick.c.o:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/src/systick.c.o
.PHONY : src/systick.c.o

src/systick.i: src/systick.c.i
.PHONY : src/systick.i

# target to preprocess a source file
src/systick.c.i:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/src/systick.c.i
.PHONY : src/systick.c.i

src/systick.s: src/systick.c.s
.PHONY : src/systick.s

# target to generate assembly for a file
src/systick.c.s:
	$(MAKE) -f CMakeFiles/stm32f103Demo.elf.dir/build.make CMakeFiles/stm32f103Demo.elf.dir/src/systick.c.s
.PHONY : src/systick.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... stm32f103Demo.elf"
	@echo "... lib/CMSIS/startup_stm32f10x_md.o"
	@echo "... lib/CMSIS/startup_stm32f10x_md.i"
	@echo "... lib/CMSIS/startup_stm32f10x_md.s"
	@echo "... lib/CMSIS/system_stm32f10x.o"
	@echo "... lib/CMSIS/system_stm32f10x.i"
	@echo "... lib/CMSIS/system_stm32f10x.s"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/misc.o"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/misc.i"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/misc.s"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.o"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.i"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.s"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.o"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.i"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.s"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.o"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.i"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.s"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.o"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.i"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.s"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.o"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.i"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.s"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.o"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.i"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.s"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.o"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.i"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.s"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.o"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.i"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.s"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.o"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.i"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.s"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.o"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.i"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.s"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.o"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.i"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.s"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.o"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.i"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.s"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.o"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.i"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.s"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.o"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.i"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.s"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.o"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.i"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.s"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.o"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.i"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.s"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.o"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.i"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.s"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.o"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.i"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.s"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.o"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.i"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.s"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.o"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.i"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.s"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.o"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.i"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.s"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.o"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.i"
	@echo "... lib/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.s"
	@echo "... lib/syscalls/syscalls.o"
	@echo "... lib/syscalls/syscalls.i"
	@echo "... lib/syscalls/syscalls.s"
	@echo "... src/dcf77.o"
	@echo "... src/dcf77.i"
	@echo "... src/dcf77.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/stm32f10x_it.o"
	@echo "... src/stm32f10x_it.i"
	@echo "... src/stm32f10x_it.s"
	@echo "... src/systick.o"
	@echo "... src/systick.i"
	@echo "... src/systick.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

